using Newtonsoft.Json;
using System.Collections.Generic;

namespace Enhanced_Handbook
{
    internal sealed class HandbookCategoriesConfig
    {
        internal const string ConfigFileName = "EnhancedHandbook.json";

        [JsonProperty("onlyGridPages")]
        public bool OnlyGridPages { get; set; } = false;

        [JsonProperty("disableTutorialTab")]
        public bool DisableTutorialTab { get; set; }

        [JsonProperty("disableBlocksAndItemsTab")]
        public bool DisableBlocksAndItemsTab { get; set; }

        [JsonProperty("disableGuidesTab")]
        public bool DisableGuidesTab { get; set; }

        [JsonProperty("disableOriginalSearchButton")]
        public bool DisableOriginalSearchButton { get; set; }

        [JsonProperty("disableDragAndDrop")]
        public bool DisableDragAndDrop { get; set; }

        [JsonProperty("enableGroupCreationHotkeys")]
        public bool EnableGroupCreationHotkeys { get; set; }

        [JsonProperty("hasSeenSetupMessage")]
        public bool HasSeenSetupMessage { get; set; }

        [JsonProperty("createVariantCategories")]
        public bool CreateVariantCategories { get; set; }

        [JsonProperty("createEverythingGrouped")]
        public bool CreateEverythingGrouped { get; set; }

        [JsonProperty("usesEnglishDefaults")]
        public bool UsesEnglishDefaults { get; set; }

        [JsonProperty("categories")]
        public List<HandbookCategoryConfigEntry> Categories { get; set; } = new();

        internal static HandbookCategoriesConfig CreateDefault()
        {
            return new HandbookCategoriesConfig
            {
                OnlyGridPages = false,
                DisableTutorialTab = true,
                DisableBlocksAndItemsTab = true,
                DisableGuidesTab = true,
                DisableOriginalSearchButton = true,
                DisableDragAndDrop = false,
                EnableGroupCreationHotkeys = false,
                CreateVariantCategories = false,
                CreateEverythingGrouped = true,
                HasSeenSetupMessage = false,
                UsesEnglishDefaults = false,
                Categories = new List<HandbookCategoryConfigEntry>
                {
                    new HandbookCategoryConfigEntry
                    {
                        Name = "Bookmarks"
                    }
                }
            };
        }

        internal static HandbookCategoriesConfig CreateWithDefaultCategories()
        {
            HandbookCategoriesConfig config = CreateDefault();
            config.UsesEnglishDefaults = true;
            config.Categories = CreateDefaultCategories();
            return config;
        }

        internal static List<HandbookCategoryConfigEntry> CreateDefaultCategories()
        {
            return new List<HandbookCategoryConfigEntry>
            {
                new HandbookCategoryConfigEntry
                {
                    Name = "Tools",
                    MatchWords = new List<string>
                    {
                        "Materializer",
                        "Toolsmithing",
                        "Grindstone",
                        "Whetstone",
                        "Polishing set",
                        "Shovel",
                        "Axe",
                        "Hoe",
                        "Knife",
                        "Pickaxe",
                        "Prospecting",
                        "Saw",
                        "Scythe",
                        "Hayfork",
                        "Shears",
                        "Cleaver",
                        "Tongs",
                        "Wrench",
                        "Hammer",
                        "Drill",
                        "Jackhammer",
                        "Crowbar",
                        "Corpse Compass",
                        "Tuning Spear",
                        "Awl",
                        "Drop Spindle",
                        "Wooden Spindle",
                        "Creaser",
                        "Ridge",
                        "Threshing",
                        "Rolling pin",
                        "Animal Cage",
                        "Sieve",
                        "Wooden Pan",
                        "Spoon",
                        "Grunter",
                        "Fishing Spear",
                        "Knitting needles",
                        "Bug net",
                        "Quill",
                        "Plumb",
                        "Flute",
                        "Whistle",
                        "Pestle",
                        "Firestarter",
                        "Spyglass",
                        "Flint and flint",
                        "Bow drill",
                        "Flint and steel",
                        "Matches",
                        "Crude lighter",
                        "Ruler"
                    },
                    MatchTitleWords = new List<string>(),
                    ForbiddenWords = new List<string>
                    {
                        "%Clutter",
                        "Rusted",
                        "Firearms",
                        "Helve",
                        "Mold",
                        "Head",
                        "Pedestal",
                        "Stand",
                        "Scrap",
                        "Blade",
                        "Long",
                        "Bit",
                        "Beam",
                        "Roof",
                        "Vessel",
                        "Ruined",
                        "Admin",
                        "mechanic"
                    },
                    ForbiddenTitleWords = new List<string>(),
                    TabBackgroundColor = "#3A1F04"
                },
                new HandbookCategoryConfigEntry
                {
                    Name = "Weapons",
                    MatchWords = new List<string>
                    {
                        "Spear",
                        "Pike",
                        "Javelin",
                        "Sword",
                        "Shortsword",
                        "Sabre",
                        "Saber",
                        "Falx",
                        "Escot",
                        "Club",
                        "Polehammer",
                        "Warhammer",
                        "Poleaxe",
                        "Halberd",
                        "Long Axe",
                        "Quarterstaff",
                        "Frying Pan",
                        "Bow",
                        "Longbow",
                        "Crossbow",
                        "Arrow",
                        "Bolt",
                        "Sling",
                        "Pistol",
                        "Bossi",
                        "Arquebus",
                        "Blunderbuss",
                        "Carbine",
                        "Musket",
                        "Bayonet",
                        "Bullet",
                        "Scrap Bomb"
                    },
                    MatchTitleWords = new List<string>(),
                    ForbiddenWords = new List<string>
                    {
                        "%Clutter",
                        "Mold",
                        "Head",
                        "Pedestal",
                        "Mounted",
                        "Mount",
                        "Rack",
                        "Stand",
                        "Parts",
                        "Sheath",
                        "Sheth",
                        "Case",
                        "Quiver",
                        "Pouch",
                        "Bone Bow",
                        "Bowtorn",
                        "Scrap",
                        "Ornate",
                        "Stirrup",
                        "Ramrod",
                        "Barrel",
                        "Fishing",
                        "Tuning",
                        "Raw",
                        "Cooked",
                        "Cat",
                        "Ruined",
                        "=item-maltiezfirearms:bayonet-blade-socket"
                    },
                    ForbiddenTitleWords = new List<string>(),
                    TabBackgroundColor = "#3A1F04"
                },
                new HandbookCategoryConfigEntry
                {
                    Name = "Armor",
                    MatchWords = new List<string>
                    {
                        "Armor",
                        "Body",
                        "Leg",
                        "Helmet",
                        "Lamellar",
                        "Jerkin",
                        "Gambeson",
                        "Breastplate",
                        "Chestplate",
                        "Helm",
                        "Cuisses",
                        "Cuirass",
                        "Scale shirt",
                        "Scale sleeves",
                        "Greaves",
                        "Pauldrons",
                        "Rerebraces",
                        "Vambraces",
                        "Brigandine",
                        "Chain coif",
                        "Chain shirt",
                        "Chain sleeves",
                        "Chain mittens"
                    },
                    MatchTitleWords = new List<string>(),
                    ForbiddenWords = new List<string>
                    {
                        "%Clutter",
                        "Shield",
                        "Stand",
                        "Boiler",
                        "Rack",
                        "Broken",
                        "Damaged",
                        "Dog",
                        "Corroded",
                        "Direwolf",
                        "Bison",
                        "mechanic"
                    },
                    ForbiddenTitleWords = new List<string>(),
                    TabBackgroundColor = "#3A1F04"
                },
                new HandbookCategoryConfigEntry
                {
                    Name = "Clothes",
                    MatchWords = new List<string>
                    {
                        "Clothes",
                        "Fur",
                        "Shirt",
                        "Blouse",
                        "Sweater",
                        "Coat",
                        "Apron",
                        "Vest",
                        "Cape",
                        "Tunic",
                        "Capelet",
                        "Jacket",
                        "Cloak",
                        "Tabbard",
                        "Bolero",
                        "Moonrobe",
                        "Poncho",
                        "Earthrobe",
                        "Pants",
                        "Trousers",
                        "Breeches",
                        "Leggings",
                        "Skirt",
                        "Gown",
                        "Boots",
                        "Shoes",
                        "Sandals",
                        "Hat",
                        "Gorget",
                        "Embroidered coif",
                        "Piece of Straw",
                        "Hood",
                        "Mask",
                        "Goggles",
                        "Glasses",
                        "Corroded Helmet",
                        "Diadem",
                        "Dress",
                        "Coronet",
                        "Nobel Fillet",
                        "Cowl",
                        "Crown",
                        "Mianguan",
                        "Litham",
                        "Gloves",
                        "Sash",
                        "Belt",
                        "Strap",
                        "Toolbelt",
                        "Waistband",
                        "Waist chain",
                        "Necklace",
                        "Choker",
                        "Amulet",
                        "Veil",
                        "Nazar",
                        "Collar",
                        "Undermask",
                        "Pillory",
                        "Lunula",
                        "Scarf",
                        "Shepherd rope",
                        "Linen rope",
                        "Rosary",
                        "Cross",
                        "Gorget",
                        "Talisman",
                        "Torc",
                        "Kaftan",
                        "Pendant",
                        "Pin",
                        "Brooch",
                        "Fibula",
                        "Blue seal",
                        "Emblem",
                        "Silver star",
                        "Bracelet",
                        "Mantle",
                        "Bangles",
                        "Barber pouch",
                        "Bracers",
                        "Bracer",
                        "Binds",
                        "Japamala",
                        "Puff",
                        "Silver chain",
                        "Manacles",
                        "Wristguard",
                        "Wraps"
                    },
                    MatchTitleWords = new List<string>(),
                    ForbiddenWords = new List<string>
                    {
                        "%Block",
                        "%Armory",
                        "%Clutter",
                        "Blanket",
                        "Rack",
                        "Stand",
                        "Open",
                        "Night",
                        "Bushbuck",
                        "Elk",
                        "Fox",
                        "Dog",
                        "Gurnard",
                        "Sling",
                        "Ammo",
                        "Rolling",
                        "Leaves",
                        "Sapling",
                        "Log",
                        "Hooks",
                        "Hare",
                        "Fern",
                        "Banana",
                        "Pondweed",
                        "Snow",
                        "Line",
                        "Ruined",
                        "Wall",
                        "Ceiling",
                        "Witch",
                        "Mourning",
                        "Scent",
                        "Bags",
                        "Chute",
                        "Saddle",
                        "Scale",
                        "Crown-of-thorns",
                        "Tag",
                        "Urchin",
                        "=item-metalchain-silver",
                        "=item-wildcrafttree:treeseed-crownofthorns"
                    },
                    ForbiddenTitleWords = new List<string>(),
                    TabBackgroundColor = "#3A1F04"
                },
                new HandbookCategoryConfigEntry
                {
                    Name = "Health",
                    MatchWords = new List<string>
                    {
                        "Making potions",
                        "Poultice",
                        "Edible Herbs",
                        "Potent Oil",
                        "Healing Oil",
                        "Vitality Flask",
                        "Stability Flask",
                        "Bandage",
                        "Clarified",
                        "Tincture",
                        "Cloudberry",
                        "Cloudberry juice",
                        "Cloudberry ambrosia",
                        "Pineapple wine",
                        "Pineapple brandy",
                        "Apple cider",
                        "Apple brandy",
                        "Appleberry wine",
                        "Crabapple cider",
                        "Cherry pits",
                        "Cherry pit",
                        "Husk cherry",
                        "Cherry brandy",
                        "Cherry juice",
                        "Cherry cider",
                        "Cherryplum wine",
                        "Strong peach cider",
                        "Aged peach cider",
                        "Fine peach cider",
                        "Vintage peach brandy",
                        "Strong orange cider",
                        "Aged orange cider",
                        "Fine orange cider",
                        "Aged false orange cider",
                        "Lychee cider",
                        "Lychee brandy",
                        "Chili pepper",
                        "Chili pepper cider",
                        "Chili pepper juice",
                        "Saguaro fruit",
                        "Halva",
                        "Pacoca",
                        "Marzipan",
                        "Paper lantern berry",
                        "Bearberry",
                        "Black nightshade",
                        "Cooked bison leg",
                        "Cooked cockatrice tail",
                        "Cooked ribs",
                        "Smoked Plain Primemeat",
                        "Cured healthy primemeat",
                        "Vintage",
                        "Smoked black",
                        "Smoked blood",
                        "Garlic",
                        "Capers",
                        "Gelatin",
                        "Candied",
                        "Candy",
                        "Fruit bar",
                        "Gozinaki",
                        "Soulstorm brew",
                        "Chocolate",
                        "Syrup",
                        "Pomegranate vinegar",
                        "Yogurt"
                    },
                    MatchTitleWords = new List<string>(),
                    ForbiddenWords = new List<string>
                    {
                        "%Block",
                        "%Meal",
                        "%Market",
                        "%Clothes",
                        "Fresh",
                        "Base",
                        "Mash",
                        "Clipping",
                        "Frozen",
                        "Ice",
                        "Tannin",
                        "Pickled capers",
                        "Pickled chili pepper",
                        "Black nightshade",
                        "Plant",
                        "Bush",
                        "Hay",
                        "Part-cooked",
                        "Part-baked",
                        "Charred",
                        "Seeds",
                        "Turk's cap",
                        "Female",
                        "Male",
                        "Mashed",
                        "Raw soy milk",
                        "Covered",
                        "Tuning",
                        "=item-feverstonewilds:cockatrice-tail-partcooked",
                        "=item-feverstonewilds:ribs-partcooked",
                        "=item-feverstonewilds:bisonleg-partcooked"
                    },
                    ForbiddenTitleWords = new List<string>(),
                    TabBackgroundColor = "#3B5D37"
                },
                new HandbookCategoryConfigEntry
                {
                    Name = "Kitchenware",
                    MatchWords = new List<string>
                    {
                        "Guide to food shelves",
                        "Mechanic: brewing",
                        "Mechanic: food preservation",
                        "Boiler",
                        "Condenser",
                        "Fireplace",
                        "Stove",
                        "Oven",
                        "Stone shelf",
                        "Stone drawers",
                        "Mixing",
                        "Rolling pin",
                        "Culinary",
                        "Meat storage",
                        "Meat rack",
                        "Spice rack",
                        "Freezer",
                        "Cooler",
                        "Frying",
                        "Wooden bucket",
                        "Metal bucket",
                        "Vegetable storage",
                        "Veggie Storage",
                        "Cabinet",
                        "Mushroom storage",
                        "Shelf",
                        "Ceiling jar",
                        "Fat storage",
                        "Bone storage",
                        "Food display",
                        "Tun",
                        "Basket",
                        "Barrel",
                        "Pumpkin case",
                        "Flour sack",
                        "Quern",
                        "Fruitpress",
                        "Pot",
                        "Cauldron",
                        "Teapot",
                        "Lufa",
                        "Crock",
                        "Bowl",
                        "Cork",
                        "Smoker",
                        "Bottle",
                        "Potion flask",
                        "Vat",
                        "Temporal butcher",
                        "Smoking",
                        "Butchering table",
                        "Skinning",
                        "Spile",
                        "Mug",
                        "Cup",
                        "Steel wool",
                        "Cut ice",
                        "Table",
                        "Cleaning vinegar"
                    },
                    MatchTitleWords = new List<string>(),
                    ForbiddenWords = new List<string>
                    {
                        "%Clutter",
                        "Burned",
                        "Body",
                        "End",
                        "Coke",
                        "Sign",
                        "Woven",
                        "Hand",
                        "Mold",
                        "Raw",
                        "Residue",
                        "Lid",
                        "Artistic",
                        "Terra",
                        "Small",
                        "Pistol",
                        "Arquebus",
                        "Blunderbuss",
                        "Musket",
                        "Carbine",
                        "Coral",
                        "Cactus",
                        "Trap",
                        "Of",
                        "Ruined",
                        "Sided",
                        "Deco",
                        "Picnic",
                        "Mail",
                        "Wine",
                        "Fish",
                        "Wooden",
                        "Wattle",
                        "Seed",
                        "Door",
                        "Mugrack",
                        "Mug rack",
                        "Kitchen shelf",
                        "Cottage core",
                        "Brass table",
                        "Yellow pot",
                        "Honey pot",
                        "Flower",
                        "Arrow",
                        "Spear",
                        "Frozen",
                        "Stick",
                        "Large",
                        "Sewing",
                        "Sugar",
                        "Blueprint",
                        "Foraging",
                        "Omok",
                        "Handle",
                        "Cloth",
                        "In a",
                        "Candelabra",
                        "Coffee",
                        "Side",
                        "Setting",
                        "Linen",
                        "Victorian",
                        "mechanic"
                    },
                    ForbiddenTitleWords = new List<string>(),
                    TabBackgroundColor = "#754646"
                },
                new HandbookCategoryConfigEntry
                {
                    Name = "Farming",
                    MatchWords = new List<string>
                    {
                        "Mechanic: farming",
                        "Mechanic: food preservation",
                        "Mechanic: greenhouse",
                        "Garden signs",
                        "Seeds",
                        "Papaya seed",
                        "Coconut seed",
                        "Mangrove apple seed",
                        "Bay laurel seed",
                        "Sal seed",
                        "Satinash seed",
                        "Raw soybeans",
                        "Raw peanuts",
                        "Amaranth grain",
                        "Spelt grain",
                        "Rice grain",
                        "Rye grain",
                        "Sunflower grain",
                        "Clipping",
                        "Tree cutting",
                        "Fruiting bodies",
                        "Grape vine",
                        "Grape Clippings",
                        "Cultivated",
                        "Hoe",
                        "Seed shelf",
                        "Seed bin",
                        "Compost",
                        "Peanut skins",
                        "Fertilizer",
                        "Earthworm",
                        "Horn shavings",
                        "Crushed eggshell",
                        "Bonemeal",
                        "Terra preta",
                        "Saltpeter",
                        "Potash",
                        "Spile",
                        "Scarecrow",
                        "Irrigation",
                        "Watering can"
                    },
                    MatchTitleWords = new List<string>(),
                    ForbiddenWords = new List<string>
                    {
                        "%Meal",
                        "Bread",
                        "Breaded",
                        "Pickled",
                        "Dry",
                        "Flour",
                        "Oil",
                        "Vessel",
                        "Amulet",
                        "Bar",
                        "Croton",
                        "Raw",
                        "Empty",
                        "Flowering",
                        "Ripe",
                        "Stem",
                        "Efflorescence",
                        "Wild vine",
                        "Head",
                        "Growing",
                        "Bucket",
                        "Juice",
                        "Brine",
                        "Solution",
                        "Wine",
                        "Brandy",
                        "Ivy",
                        "Woodbine",
                        "Bryony",
                        "Virgin",
                        "Common grape",
                        "Roasted",
                        "Ruined",
                        "Mature",
                        "Mold",
                        "Grassy",
                        "Patches of grass",
                        "Sparse grass",
                        "Trampled",
                        "Trail",
                        "Road",
                        "Highway",
                        "=block-saltpeter-d",
                        "=item-grain-flax",
                        "=item-grain-sunflower",
                        "=block-primitivesurvival:earthwormcastings",
                        "=block-wildcraftfruit:fruitvine-blackgrape-ripe-north",
                        "=block-wildcraftfruit:fruitvine-redgrape-ripe-north",
                        "=block-wildcraftfruit:fruitvine-whitegrape-ripe-north",
                        "=block-wildcraftfruit:fruitvine-foxgrape-ripe-north",
                        "mechanic"
                    },
                    ForbiddenTitleWords = new List<string>(),
                    TabBackgroundColor = "#754646"
                },
                new HandbookCategoryConfigEntry
                {
                    Name = "Cooking",
                    MatchWords = new List<string>
                    {
                        "Expanded foods: cooking",
                        "Mechanic: brewing",
                        "Kneading",
                        "Simmering",
                        "Arts guides",
                        "Artillery: cooking",
                        "Meal making",
                        "Mechanic: Thirst",
                        "Mechanic: cheese making",
                        "%Meal",
                        "Cured",
                        "Cultured soybeans",
                        "Smoked",
                        "Candied",
                        "Candy",
                        "Dehydrated",
                        "Dried",
                        "Roasted",
                        "Pickled",
                        "Cooked",
                        "Bar",
                        "Fried",
                        "Baked",
                        "Boiled",
                        "Hardboiled",
                        "Water-glassed",
                        "Blown",
                        "Tender aged",
                        "Deluxe",
                        "Sweetened",
                        "Water",
                        "Clarified",
                        "Cider",
                        "Perry",
                        "Grenadine",
                        "Sake",
                        "Mead",
                        "Whiskey",
                        "Wine",
                        "Juice",
                        "Brandy",
                        "Liqueur",
                        "Cognac",
                        "Calvados",
                        "Guignolet",
                        "Amaretto",
                        "Nocino",
                        "Armagnac",
                        "Ale",
                        "Smreka",
                        "Borovicka",
                        "Vodka",
                        "Honeyjack",
                        "Tequila",
                        "Aquamiel",
                        "Pulque",
                        "Aqua Vitae",
                        "Milk",
                        "Ambrosia",
                        "Soulstorm brew",
                        "Limeade",
                        "Lemonade",
                        "Puree",
                        "Slush",
                        "Brine",
                        "Blood",
                        "Paste",
                        "Sauce",
                        "Dressing",
                        "Oil",
                        "Lard",
                        "Yogurt",
                        "Kefir",
                        "Sushi",
                        "Chocolate",
                        "Trail mix",
                        "Cheese",
                        "Blood sausage",
                        "Black pudding",
                        "Bread",
                        "Oatbread",
                        "Cornbread",
                        "Bloodbread",
                        "Flatbread",
                        "Pastry dough base",
                        "Shawarma",
                        "Hardtack",
                        "Hardertack",
                        "Hardesttack",
                        "Irontack",
                        "Syrup-covered muffin",
                        "Bun",
                        "Caviar",
                        "Yeast",
                        "Gozinaki",
                        "Pasta",
                        "Lavash",
                        "Dumplings",
                        "Cooked pemmican",
                        "Salad dressing",
                        "Pacoca",
                        "Cocoa powder",
                        "Tofu",
                        "Butter",
                        "Vanilla extract",
                        "Vinegar",
                        "Jerky"
                    },
                    MatchTitleWords = new List<string>(),
                    ForbiddenWords = new List<string>
                    {
                        "Partbaked",
                        "Partcooked",
                        "Charred",
                        "Boiling",
                        "Oiled",
                        "Breaded",
                        "1 slice",
                        "Sea water",
                        "Hot water",
                        "Rain",
                        "Cuttings",
                        "Cutting",
                        "Flask",
                        "Well",
                        "Still",
                        "Crowfoot",
                        "Lily",
                        "Milfoil",
                        "Lettuce",
                        "Primrose",
                        "Plant",
                        "Wine cup",
                        "Raw",
                        "Frozen",
                        "Bonemeal",
                        "Fangs",
                        "Horns",
                        "Solder",
                        "Lamp",
                        "Male",
                        "Female",
                        "Buck",
                        "Doe",
                        "Calf",
                        "Fawn",
                        "Dough",
                        "Shelf",
                        "Basket",
                        "Box",
                        "Teleporter",
                        "Frit",
                        "Cleaning",
                        "Ice cubes",
                        "mechanic"
                    },
                    ForbiddenTitleWords = new List<string>(),
                    TabBackgroundColor = "#754646"
                },
                new HandbookCategoryConfigEntry
                {
                    Name = "Livestock",
                    MatchWords = new List<string>
                    {
                        "Game mechanic: animal",
                        "Mechanic: tamed mountable",
                        "%Goat",
                        "%Deer",
                        "Giant deer",
                        "Caribou",
                        "American mountain deer",
                        "Mule deer",
                        "Huemul",
                        "Dakota palm deer",
                        "Antifer's deer",
                        "Stag moose",
                        "Aurochs",
                        "Nilgai",
                        "Buffalo",
                        "Tamaraw",
                        "Anoa",
                        "Saola",
                        "Eland",
                        "Nyala",
                        "Bongo",
                        "Kudu",
                        "Bushbuck",
                        "Sitatunga",
                        "Rhinoceros",
                        "Hare",
                        "Jackrabbit",
                        "Hen",
                        "Rooster",
                        "Duck",
                        "Bighorn",
                        "Boar",
                        "Sow",
                        "Yak",
                        "Pheasant",
                        "Turkey",
                        "Capercaillies",
                        "Bison",
                        "Fresh grass",
                        "Dry grass",
                        "Peanut skins",
                        "Egg shells",
                        "Feed",
                        "Carrot bundle",
                        "Straw",
                        "Porcupine grass bundle",
                        "Saltmarsh bulrush",
                        "Papaya seed",
                        "Walnut seed",
                        "Oldman saltbush seeds",
                        "Yew seed",
                        "Honey locust seed",
                        "Umnini seed",
                        "Banyan seed",
                        "Beech seed",
                        "Bearnut seed",
                        "Tamanu seed",
                        "Satinash seed",
                        "Sal seed",
                        "Maize",
                        "Bale",
                        "Flax seeds",
                        "Red oat",
                        "Cattails",
                        "Mash",
                        "Tender birch leaves",
                        "Willow leaves",
                        "Sourwood leaves",
                        "Earthworm",
                        "Fence",
                        "Gate",
                        "Trough",
                        "Henbox",
                        "Nestbox",
                        "Crafted duck nest",
                        "Animal cage",
                        "Large bird nest",
                        "Ovulated",
                        "Compost bin",
                        "Pile of fresh manure",
                        "Ceramic egg"
                    },
                    MatchTitleWords = new List<string>(),
                    ForbiddenWords = new List<string>
                    {
                        "%Clothes",
                        "Egg",
                        "Eggs",
                        "Pie",
                        "Cheddar",
                        "Cheese",
                        "Milk",
                        "Dead",
                        "Broken",
                        "Liquid",
                        "Horns",
                        "Antlers",
                        "Foot",
                        "Parts",
                        "Spear",
                        "Piece of",
                        "Ear",
                        "Paddy",
                        "Dummy",
                        "Head mount",
                        "Pelt",
                        "Taxidermy",
                        "Array",
                        "Fern",
                        "Linen",
                        "Chopped",
                        "Cooked",
                        "Skins",
                        "Oil",
                        "Seed bar",
                        "Rusty",
                        "Bolts",
                        "Strewn",
                        "By",
                        "Bed",
                        "Ruined",
                        "Hare grass",
                        "Hide",
                        "Rhinoceros bush",
                        "Storage",
                        "Growing",
                        "Mature",
                        "Raw",
                        "Charred",
                        "Tall",
                        "Eaten",
                        "Bins",
                        "Shelf",
                        "3x3",
                        "4x4",
                        "5x5",
                        "8x5",
                        "Rusted",
                        "Roof",
                        "Roofing",
                        "Kid",
                        "Calf",
                        "Fawn",
                        "Lamb",
                        "Duckling",
                        "Bear",
                        "Piglet",
                        "Water deer",
                        "Pampas",
                        "Pudu",
                        "Red brocket",
                        "Taruca deer",
                        "Ibex",
                        "Mountain anoa",
                        "Earthworm",
                        "Flour",
                        "Honeycomb",
                        "mechanic"
                    },
                    ForbiddenTitleWords = new List<string>(),
                    TabBackgroundColor = "#294444"
                },
                new HandbookCategoryConfigEntry
                {
                    Name = "Beekeeping",
                    MatchWords = new List<string>
                    {
                        "Apiculture",
                        "Wild beehive",
                        "Bee hive",
                        "Ceramic hive",
                        "Langstroth",
                        "Lined frame",
                        "Waxed twine",
                        "Skep",
                        "Honey pot",
                        "Brood pot",
                        "Beenade",
                        "Bees sign",
                        "Honey storage"
                    },
                    MatchTitleWords = new List<string>(),
                    ForbiddenWords = new List<string>
                    {
                        "Raw",
                        "Harvestable",
                        "Populated"
                    },
                    ForbiddenTitleWords = new List<string>(),
                    TabBackgroundColor = "#294444"
                },
                new HandbookCategoryConfigEntry
                {
                    Name = "Pets and Mounts",
                    MatchWords = new List<string>
                    {
                        "Taming",
                        "Mod mechanic",
                        "Aurochs domestication",
                        "Mechanical companion",
                        "Restoration kit",
                        "Taming spear",
                        "Cockatrice",
                        "Direwolf",
                        "Ostrich",
                        "Elk",
                        "Moose",
                        "Reindeer",
                        "Elephant",
                        "Mammoth",
                        "Jackal",
                        "Dhole",
                        "Wolf",
                        "Corgi",
                        "German shepherd",
                        "Hunting",
                        "Dingo",
                        "Coyote",
                        "Dog",
                        "Wolfdog",
                        "Horse",
                        "Donkey",
                        "Mare",
                        "Stallion",
                        "Horseshoes",
                        "Saddle",
                        "Saddleblanket",
                        "Pet",
                        "Flute",
                        "Medallion",
                        "Ocelot",
                        "Serval",
                        "Cat (female)",
                        "Cat (male)",
                        "Wild cat"
                    },
                    MatchTitleWords = new List<string>(),
                    ForbiddenWords = new List<string>
                    {
                        "%Clothes",
                        "Shorteared",
                        "Maned",
                        "South american",
                        "Bush",
                        "Foal",
                        "Calf",
                        "Colt",
                        "Filly",
                        "Chestnut",
                        "Kitten",
                        "Chick",
                        "Fox",
                        "Pup",
                        "Bull elk",
                        "Cow elk",
                        "Forest",
                        "Svalbard",
                        "Scimitar",
                        "Charred",
                        "Saber",
                        "Taxidermy",
                        "Pelt",
                        "Head mount",
                        "Raccoon",
                        "Figurehead",
                        "Glider",
                        "Food",
                        "Dead",
                        "Blood",
                        "Fish",
                        "Schematic",
                        "Component",
                        "Supply",
                        "Wheels",
                        "Raw",
                        "Cooked",
                        "Egg",
                        "Eggs",
                        "Lichen",
                        "Carcass",
                        "Cheddar",
                        "Dough",
                        "Part bake",
                        "Cooked",
                        "Elfin",
                        "Dryad",
                        "Cheese",
                        "Milk",
                        "Painting",
                        "Hide",
                        "Rack",
                        "Antlers"
                    },
                    ForbiddenTitleWords = new List<string>(),
                    TabBackgroundColor = "#294444"
                },
                new HandbookCategoryConfigEntry
                {
                    Name = "Travel",
                    MatchWords = new List<string>
                    {
                        "Sailboat",
                        "Boat tag",
                        "Boat seat",
                        "Canoe",
                        "Raft",
                        "Cart",
                        "Canopy",
                        "Cratechest",
                        "Barrelchest",
                        "Small basket",
                        "Small sack",
                        "Small chest",
                        "Small pouch",
                        "Sidetent",
                        "Sideboards",
                        "Sideboard",
                        "Leather sides",
                        "Woven sides",
                        "Marketstall",
                        "Sled",
                        "Wheelbarrow",
                        "Stag",
                        "Figurehead"
                    },
                    MatchTitleWords = new List<string>(),
                    ForbiddenWords = new List<string>
                    {
                        "%Clutter",
                        "Frame",
                        "Unfinished",
                        "Admin",
                        "Blueprint",
                        "Materializer",
                        "Blueprints",
                        "mechanic"
                    },
                    ForbiddenTitleWords = new List<string>(),
                    TabBackgroundColor = "#49150F"
                },
                new HandbookCategoryConfigEntry
                {
                    Name = "Construction",
                    MatchWords = new List<string>
                    {
                        "Mechanic: mechanical power",
                        "Mechanic: steelmaking",
                        "Mechanic: coke oven",
                        "Mechanic: smelting",
                        "Mechanic: beehive kiln",
                        "Mechanic: Charcoal burning",
                        "Mechanic: Smelting",
                        "Mechanic: Wells",
                        "Waterwheel mechanical power",
                        "Well spring",
                        "Boiler",
                        "Pipe",
                        "Hand pump",
                        "Shutoff valve",
                        "Condenser",
                        "Spinning Wheel",
                        "Chute",
                        "Screw",
                        "Hopper",
                        "Winch",
                        "Portcullis",
                        "Floorplate",
                        "Pottery Wheel",
                        "Penstock",
                        "Quern"
                    },
                    MatchTitleWords = new List<string>(),
                    ForbiddenWords = new List<string>
                    {
                        "%Clutter",
                        "Frame",
                        "Door",
                        "Body",
                        "End",
                        "mechanic"
                    },
                    ForbiddenTitleWords = new List<string>(),
                    TabBackgroundColor = "#49150F"
                },
                new HandbookCategoryConfigEntry
                {
                    Name = "Power",
                    MatchWords = new List<string>
                    {
                        "Electricity: Current",
                        "Electricity: Motors",
                        "Electricity: ElectricalProgressive",
                        "Windmill",
                        "Sail",
                        "Passthrough",
                        "Axle",
                        "Brake",
                        "Mechanical power",
                        "Clutch",
                        "Wooden gear",
                        "Transmission",
                        "Angled gears",
                        "Large gear Section",
                        "Waterwheel",
                        "Flume",
                        "Electricity",
                        "Generator",
                        "Thermoelectric",
                        "Motor",
                        "Battery",
                        "Cable",
                        "Transformer",
                        "Charging station",
                        "Electrical switch",
                        "Helve Hammer",
                        "Pulverizer"
                    },
                    MatchTitleWords = new List<string>(),
                    ForbiddenWords = new List<string>
                    {
                        "Palm",
                        "Kneeding",
                        "Burned",
                        "Mold",
                        "Head",
                        "Toggle",
                        "Pounder",
                        "Section",
                        "Frame",
                        "Mechanical"
                    },
                    ForbiddenTitleWords = new List<string>(),
                    TabBackgroundColor = "#B8860B"
                }
            };
        }
    }

    internal sealed class HandbookCategoryConfigEntry
    {
        [JsonProperty("name")]
        public string Name { get; set; } = string.Empty;

        [JsonProperty("matchWords")]
        public List<string> MatchWords { get; set; } = new();

        [JsonProperty("matchTitleWords")]
        public List<string> MatchTitleWords { get; set; } = new();

        [JsonProperty("forbiddenWords")]
        public List<string> ForbiddenWords { get; set; } = new();

        [JsonProperty("forbiddenTitleWords")]
        public List<string> ForbiddenTitleWords { get; set; } = new();

        [JsonProperty("tabBackgroundColor")]
        public string TabBackgroundColor { get; set; } = HandbookCategoryColors.DefaultColorName;
    }
}
